server:
  port: 1700

spring:

  application:
    name: FBVISITOR-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroServiceProjects
    username: postgres
    password: Akash8@71#26

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  config:
    import: optional:configserver:http://localhost:1704

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka




